# Generated by Django 5.0.2 on 2024-05-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postmodel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='likes',
        ),
    ]
