# Generated by Django 5.0.2 on 2024-05-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postmodel_about_user_postmodel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='about_user',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='city',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
