# Generated by Django 5.0.2 on 2024-05-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_savecontact_alter_profilemodel_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='savecontact',
            new_name='save',
        ),
    ]
